version: '3.8'

services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gabriel/data/mariadb
      
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gabriel/data/wordpress

networks:
  inception:
    name: inception
    driver: bridge